// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "a08a04b7-c804-4c12-8c9b-6ba7ad71fa7d");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1741344781);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1736956283);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{bd55985a-f54a-4e50-8369-bee0c174c6b6}");
user_pref("browser.disableResetPrompt", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1736956274);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.meta_refresh_when_inactive.disabled", true);
user_pref("browser.migration.version", 152);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f0afe3da-536f-43e8-9a15-bde6d5cf3df0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.reader.detectedFirstArticle", false);
user_pref("browser.region.update.updated", 1736956275);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1741344781992");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1741366381992");
user_pref("browser.search.region", "BE");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.defaultBrowserCheckCount", 100);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1736956280");
user_pref("browser.shell.mostRecentDefaultPromptSeen", "1365509001307");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "https://kubernetes.io/docs");
user_pref("browser.startup.homepage_override.buildID", "20250113121357");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.startup.lastColdStartupCheck", 1741344789);
user_pref("browser.topsites.contile.cacheValidFor", 11921);
user_pref("browser.topsites.contile.lastFetch", 1741344790);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"vertical-spacer\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":21,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 100);
user_pref("captchadetection.lastSubmission", 1741344);
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("datareporting.healthreport.service.firstRun", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1365509001307");
user_pref("datareporting.usage.uploadEnabled", false);
user_pref("distribution.iniFile.exists.appversion", "136.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mozilla-deb.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "8909ad0d5aeb4ba5a741ee9434eef507");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECPaojx/l0T3hBAiOIy3WsynD6g==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250227124745");
user_pref("extensions.lastAppVersion", "136.0");
user_pref("extensions.lastPlatformVersion", "136.0");
user_pref("extensions.pendingOperations", true);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8c16d5e9-bc19-4949-a1a3-c4ab6cc6f8f1\",\"pictureinpicture@mozilla.org\":\"b7cf5959-4e26-492a-a59e-178363b73c82\",\"screenshots@mozilla.org\":\"6bec539b-7544-4163-aa85-f8fbb86c55cc\",\"webcompat-reporter@mozilla.org\":\"bd5df05b-98e5-4bb7-9524-6976ecceae40\",\"webcompat@mozilla.org\":\"c796ee0f-f37f-481d-9e18-76de960415c1\",\"default-theme@mozilla.org\":\"abd30845-d0e2-4b83-8361-33ca6b294122\",\"addons-search-detection@mozilla.com\":\"a9390b22-a2a3-4984-83d2-d9c56d12955a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("identity.fxaccounts.toolbar.defaultVisible", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("sidebar.backupState", "{\"width\":\"\",\"command\":\"\"}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECFpH9Ux2OxocBAiRQp30/E5KpQ==");
user_pref("toolkit.startup.last_success", 1704390509);
user_pref("toolkit.startup.recent_crashes", 1);
user_pref("toolkit.telemetry.cachedClientID", "f87159b1-80df-4aaf-9d95-830428c65bfa");
user_pref("toolkit.telemetry.cachedProfileGroupID", "233ba21f-b1fc-4a3d-8b1b-3716cd7b6bb2");
user_pref("toolkit.telemetry.previousBuildID", "20250227124745");
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
